safe: false

# Blog Settings
author: Priya M.
description: Finding My Adventure
url: http://ohpriya.com/blog/"
baseurl: "/blog/"
title: Finding My Adventure
subscribe_rss: http://ohpriya.com/blog/atom.xml/

## --- Octopress defaults --- ##
# Default extensions for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages, found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft


# Github repositories
github_user: coffeenutsthemes
github_repo_url: https://github.com/coffeenutsthemes/ohpriya.com

# Google Analytics
google_analytics_tracking_id: UA-89505908-1

kramdown:
  hard_wrap: false

# Jekyll Settings

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:date/:title/
    
paginate_path: "/blog/page/:num"
category_dir: categories

feed:
  path: atom.xml

# language settings
isolang: en

# How many articles do you wish to appear on the front page:
paginate: 3

# exclude files
exclude:
  - LICENSE
  - README.md
